### ISSUE TITLE
Input Data

### ISSUE THREAD

**Issue by ColemanKobe** [Allegheny-Ethical-CS/GatorMiner#49]
This epic will constitute issues that involve visual and technical enhancement of the aspects of the project that deal with input data.

**Comment by noorbuchi** [comment]
Hello @ColemanKobe, thanks for working on this. I have a few questions/concerns about this. I'm assuming that this epic is related to #47 and to #37. Since the issue is not a major addition to the project, it should not be added as an epic. Also, the time period and deadline you added is too long for a feature like this. The file upload is already supported by Streamlit and adding it should not take that long. Please check out the documentation [here](https://docs.streamlit.io/en/stable/api.html#streamlit.file_uploader) to see how you could start. Feel free to let me or the other TLs know if you have any questions. Thanks!
